name: pregnopal
description: "A new Flutter project."

publish_to: "none"
environment:
  sdk: ^3.5.0
version: 1.0.0+1

# Custom scripts that can be run using the command `rps script_name` followed by the script name.
scripts:
  build:
    dart run build_runner build --delete-conflicting-outputs
    # Runs code generation (e.g., for Freezed or JSON serialization) with build_runner.
    # The `--delete-conflicting-outputs` flag ensures any conflicting files are removed before generating new ones.
  watch:
    dart run build_runner watch --delete-conflicting-outputs
    # Similar to `build`, but watches for changes in the source files and automatically regenerates code as needed.
  clean:
    flutter clean && flutter pub get && dart fix --apply && dart format .
    # Cleans the build directory, fetches dependencies, and applies Dart fixes automatically.
  gen:
    dart run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart
    # Runs the FlutterGen code generator to generate assets, fonts, and other static resources.
  fix:
    dart fix --apply
    # Automatically applies Dart fixes to the project.
  format:
    dart format .
    # Automatically formats all Dart files in the project.
  apk-d:
    flutter build apk --release --target lib/main_development.dart
    # Build apk in development mode
  run-r:
    flutter run --release --target lib/main_production.dart
    # Run the app in release mode
  run-d:
    flutter run --debug --target lib/main_production.dart
    # Run the app in debug mode


dependencies:
  flutter:
    sdk: flutter

  # Local Packages
  persistent_storage:
    path: packages/storage/persistent_storage
  secure_storage:
    path: packages/storage/secure_storage

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  fpdart: ^1.1.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.2.1
  auto_route: ^9.2.2
  intl: ^0.19.0
  vector_graphics: any
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  overlay_support: ^2.1.0
  flutter_draft: ^1.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  firebase_core: ^3.8.0
  flutter_local_notifications: ^18.0.1
  firebase_core_platform_interface: ^5.3.0
  qr_flutter: ^4.1.0
  flutter_typeahead: ^5.2.0
  firebase_messaging: ^15.1.5
  collection: ^1.18.0
  device_info_plus: ^11.1.1
  flutter_markdown: ^0.7.4+3
  table_calendar: ^3.1.3
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  pretty_dio_logger: ^1.4.0
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  device_preview: ^1.2.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  hive_generator: ^2.0.1
  flutter_gen: ^5.8.0

flutter_gen:
  output: lib/generated

flutter:
  uses-material-design: true

  assets:
    - local.env
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icon/
    - assets/translations/
