name: secure_storage
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
