import 'custom_app_color.dart';

@Deprecated('Use CustomAppColor instead')
class OldPrimitiveColors {
  static const CustomAppColor grey0 = CustomAppColor(0xFF000000);
  static const CustomAppColor grey20 = CustomAppColor(0xFF050505);
  static const CustomAppColor grey40 = CustomAppColor(0xFF0a0a0a);
  static const CustomAppColor grey60 = CustomAppColor(0xFF0f0f0f);
  static const CustomAppColor grey80 = CustomAppColor(0xFF141414);
  static const CustomAppColor grey100 = CustomAppColor(0xFF191919);
  static const CustomAppColor grey110 = CustomAppColor(0xFF1c1c1c);
  static const CustomAppColor grey120 = CustomAppColor(0xFF1e1e1e);
  static const CustomAppColor grey130 = CustomAppColor(0xFF212121);
  static const CustomAppColor grey140 = CustomAppColor(0xFF232323);
  static const CustomAppColor grey150 = CustomAppColor(0xFF262626);
  static const CustomAppColor grey160 = CustomAppColor(0xFF282828);
  static const CustomAppColor grey170 = CustomAppColor(0xFF2b2b2b);
  static const CustomAppColor grey180 = CustomAppColor(0xFF2d2d2d);
  static const CustomAppColor grey190 = CustomAppColor(0xFF303030);
  static const CustomAppColor grey200 = CustomAppColor(0xFF333333);
  static const CustomAppColor grey220 = CustomAppColor(0xFF383838);
  static const CustomAppColor grey240 = CustomAppColor(0xFF3d3d3d);
  static const CustomAppColor grey260 = CustomAppColor(0xFF424242);
  static const CustomAppColor grey280 = CustomAppColor(0xFF474747);
  static const CustomAppColor grey300 = CustomAppColor(0xFF4c4c4c);
  static const CustomAppColor grey350 = CustomAppColor(0xFF595959);
  static const CustomAppColor grey400 = CustomAppColor(0xFF666666);
  static const CustomAppColor grey450 = CustomAppColor(0xFF727272);
  static const CustomAppColor grey500 = CustomAppColor(0xFF7f7f7f);
  static const CustomAppColor grey550 = CustomAppColor(0xFF8c8c8c);
  static const CustomAppColor grey600 = CustomAppColor(0xFF999999);
  static const CustomAppColor grey650 = CustomAppColor(0xFFa5a5a5);
  static const CustomAppColor grey700 = CustomAppColor(0xFFb2b2b2);
  static const CustomAppColor grey750 = CustomAppColor(0xFFbfbfbf);
  static const CustomAppColor grey800 = CustomAppColor(0xFFcccccc);
  static const CustomAppColor grey810 = CustomAppColor(0xFFcecece);
  static const CustomAppColor grey820 = CustomAppColor(0xFFd1d1d1);
  static const CustomAppColor grey830 = CustomAppColor(0xFFd3d3d3);
  static const CustomAppColor grey840 = CustomAppColor(0xFFd6d6d6);
  static const CustomAppColor grey850 = CustomAppColor(0xFFd8d8d8);
  static const CustomAppColor grey860 = CustomAppColor(0xFFdbdbdb);
  static const CustomAppColor grey870 = CustomAppColor(0xFFdddddd);
  static const CustomAppColor grey880 = CustomAppColor(0xFFe0e0e0);
  static const CustomAppColor grey890 = CustomAppColor(0xFFe2e2e2);
  static const CustomAppColor grey900 = CustomAppColor(0xFFe5e5e5);
  static const CustomAppColor grey910 = CustomAppColor(0xFFe8e8e8);
  static const CustomAppColor grey920 = CustomAppColor(0xFFeaeaea);
  static const CustomAppColor grey930 = CustomAppColor(0xFFededed);
  static const CustomAppColor grey940 = CustomAppColor(0xFFefefef);
  static const CustomAppColor grey950 = CustomAppColor(0xFFf2f2f2);
  static const CustomAppColor grey960 = CustomAppColor(0xFFf4f4f4);
  static const CustomAppColor grey970 = CustomAppColor(0xFFf7f7f7);
  static const CustomAppColor grey980 = CustomAppColor(0xFFf9f9f9);
  static const CustomAppColor grey990 = CustomAppColor(0xFFfcfcfc);
  static const CustomAppColor grey1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor greyVariant0 = CustomAppColor(0xFF000000);
  static const CustomAppColor greyVariant20 = CustomAppColor(0xFF040405);
  static const CustomAppColor greyVariant40 = CustomAppColor(0xFF09090a);
  static const CustomAppColor greyVariant60 = CustomAppColor(0xFF0e0e10);
  static const CustomAppColor greyVariant80 = CustomAppColor(0xFF131315);
  static const CustomAppColor greyVariant100 = CustomAppColor(0xFF18181a);
  static const CustomAppColor greyVariant110 = CustomAppColor(0xFF1a1b1d);
  static const CustomAppColor greyVariant120 = CustomAppColor(0xFF1c1d20);
  static const CustomAppColor greyVariant130 = CustomAppColor(0xFF1f2022);
  static const CustomAppColor greyVariant140 = CustomAppColor(0xFF212225);
  static const CustomAppColor greyVariant150 = CustomAppColor(0xFF242528);
  static const CustomAppColor greyVariant160 = CustomAppColor(0xFF26272a);
  static const CustomAppColor greyVariant170 = CustomAppColor(0xFF292a2d);
  static const CustomAppColor greyVariant180 = CustomAppColor(0xFF2b2c30);
  static const CustomAppColor greyVariant190 = CustomAppColor(0xFF2d2f33);
  static const CustomAppColor greyVariant200 = CustomAppColor(0xFF303135);
  static const CustomAppColor greyVariant220 = CustomAppColor(0xFF35363b);
  static const CustomAppColor greyVariant240 = CustomAppColor(0xFF393b40);
  static const CustomAppColor greyVariant260 = CustomAppColor(0xFF3e4045);
  static const CustomAppColor greyVariant280 = CustomAppColor(0xFF43454b);
  static const CustomAppColor greyVariant300 = CustomAppColor(0xFF484a50);
  static const CustomAppColor greyVariant350 = CustomAppColor(0xFF54575e);
  static const CustomAppColor greyVariant400 = CustomAppColor(0xFF60636b);
  static const CustomAppColor greyVariant450 = CustomAppColor(0xFF6c7078);
  static const CustomAppColor greyVariant500 = CustomAppColor(0xFF787c86);
  static const CustomAppColor greyVariant550 = CustomAppColor(0xFF868992);
  static const CustomAppColor greyVariant600 = CustomAppColor(0xFF93969e);
  static const CustomAppColor greyVariant650 = CustomAppColor(0xFFa0a3aa);
  static const CustomAppColor greyVariant700 = CustomAppColor(0xFFaeb0b6);
  static const CustomAppColor greyVariant750 = CustomAppColor(0xFFbbbdc2);
  static const CustomAppColor greyVariant800 = CustomAppColor(0xFFc9cace);
  static const CustomAppColor greyVariant810 = CustomAppColor(0xFFcbcdd1);
  static const CustomAppColor greyVariant820 = CustomAppColor(0xFFced0d3);
  static const CustomAppColor greyVariant830 = CustomAppColor(0xFFd1d2d5);
  static const CustomAppColor greyVariant840 = CustomAppColor(0xFFd4d5d8);
  static const CustomAppColor greyVariant850 = CustomAppColor(0xFFd6d7da);
  static const CustomAppColor greyVariant860 = CustomAppColor(0xFFd9dadd);
  static const CustomAppColor greyVariant870 = CustomAppColor(0xFFdcdddf);
  static const CustomAppColor greyVariant880 = CustomAppColor(0xFFdedfe2);
  static const CustomAppColor greyVariant890 = CustomAppColor(0xFFe1e2e4);
  static const CustomAppColor greyVariant900 = CustomAppColor(0xFFe4e4e6);
  static const CustomAppColor greyVariant910 = CustomAppColor(0xFFe6e7e9);
  static const CustomAppColor greyVariant920 = CustomAppColor(0xFFe9eaeb);
  static const CustomAppColor greyVariant930 = CustomAppColor(0xFFececee);
  static const CustomAppColor greyVariant940 = CustomAppColor(0xFFeeeff0);
  static const CustomAppColor greyVariant950 = CustomAppColor(0xFFf1f1f2);
  static const CustomAppColor greyVariant960 = CustomAppColor(0xFFf4f4f5);
  static const CustomAppColor greyVariant970 = CustomAppColor(0xFFf6f7f7);
  static const CustomAppColor greyVariant980 = CustomAppColor(0xFFf9f9fa);
  static const CustomAppColor greyVariant990 = CustomAppColor(0xFFfcfcfc);
  static const CustomAppColor greyVariant1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor error0 = CustomAppColor(0xFF000000);
  static const CustomAppColor error20 = CustomAppColor(0xFF080101);
  static const CustomAppColor error40 = CustomAppColor(0xFF110302);
  static const CustomAppColor error60 = CustomAppColor(0xFF1a0504);
  static const CustomAppColor error80 = CustomAppColor(0xFF220705);
  static const CustomAppColor error100 = CustomAppColor(0xFF2b0807);
  static const CustomAppColor error110 = CustomAppColor(0xFF300908);
  static const CustomAppColor error120 = CustomAppColor(0xFF340a08);
  static const CustomAppColor error130 = CustomAppColor(0xFF380b09);
  static const CustomAppColor error140 = CustomAppColor(0xFF3d0c0a);
  static const CustomAppColor error150 = CustomAppColor(0xFF410d0a);
  static const CustomAppColor error160 = CustomAppColor(0xFF450e0b);
  static const CustomAppColor error170 = CustomAppColor(0xFF4a0f0c);
  static const CustomAppColor error180 = CustomAppColor(0xFF4e100d);
  static const CustomAppColor error190 = CustomAppColor(0xFF53110d);
  static const CustomAppColor error200 = CustomAppColor(0xFF57110e);
  static const CustomAppColor error220 = CustomAppColor(0xFF601310);
  static const CustomAppColor error240 = CustomAppColor(0xFF681511);
  static const CustomAppColor error260 = CustomAppColor(0xFF711713);
  static const CustomAppColor error280 = CustomAppColor(0xFF7a1914);
  static const CustomAppColor error300 = CustomAppColor(0xFF831a15);
  static const CustomAppColor error350 = CustomAppColor(0xFF981f19);
  static const CustomAppColor error400 = CustomAppColor(0xFFae231d);
  static const CustomAppColor error450 = CustomAppColor(0xFFc42820);
  static const CustomAppColor error500 = CustomAppColor(0xFFda2c24);
  static const CustomAppColor error550 = CustomAppColor(0xFFde413a);
  static const CustomAppColor error600 = CustomAppColor(0xFFe15650);
  static const CustomAppColor error650 = CustomAppColor(0xFFe56b66);
  static const CustomAppColor error700 = CustomAppColor(0xFFe9807b);
  static const CustomAppColor error750 = CustomAppColor(0xFFec9591);
  static const CustomAppColor error800 = CustomAppColor(0xFFf0aaa7);
  static const CustomAppColor error810 = CustomAppColor(0xFFf1afab);
  static const CustomAppColor error820 = CustomAppColor(0xFFf1b3b0);
  static const CustomAppColor error830 = CustomAppColor(0xFFf2b7b4);
  static const CustomAppColor error840 = CustomAppColor(0xFFf3bbb9);
  static const CustomAppColor error850 = CustomAppColor(0xFFf4bfbd);
  static const CustomAppColor error860 = CustomAppColor(0xFFf4c4c1);
  static const CustomAppColor error870 = CustomAppColor(0xFFf5c8c6);
  static const CustomAppColor error880 = CustomAppColor(0xFFf6ccca);
  static const CustomAppColor error890 = CustomAppColor(0xFFf6d0ce);
  static const CustomAppColor error900 = CustomAppColor(0xFFf7d4d3);
  static const CustomAppColor error910 = CustomAppColor(0xFFf8d9d7);
  static const CustomAppColor error920 = CustomAppColor(0xFFf9dddc);
  static const CustomAppColor error930 = CustomAppColor(0xFFf9e1e0);
  static const CustomAppColor error940 = CustomAppColor(0xFFfae5e4);
  static const CustomAppColor error950 = CustomAppColor(0xFFfbe9e9);
  static const CustomAppColor error960 = CustomAppColor(0xFFfceeed);
  static const CustomAppColor error970 = CustomAppColor(0xFFfcf2f1);
  static const CustomAppColor error980 = CustomAppColor(0xFFfdf6f6);
  static const CustomAppColor error990 = CustomAppColor(0xFFfefafa);
  static const CustomAppColor error1000 = CustomAppColor(0xFFfeffff);
  static const CustomAppColor primary0 = CustomAppColor(0xFF000000);
  static const CustomAppColor primary20 = CustomAppColor(0xFF040603);
  static const CustomAppColor primary40 = CustomAppColor(0xFF090c07);
  static const CustomAppColor primary60 = CustomAppColor(0xFF0e120b);
  static const CustomAppColor primary80 = CustomAppColor(0xFF13190f);
  static const CustomAppColor primary100 = CustomAppColor(0xFF181f13);
  static const CustomAppColor primary110 = CustomAppColor(0xFF1a2215);
  static const CustomAppColor primary120 = CustomAppColor(0xFF1d2517);
  static const CustomAppColor primary130 = CustomAppColor(0xFF1f2819);
  static const CustomAppColor primary140 = CustomAppColor(0xFF222b1b);
  static const CustomAppColor primary150 = CustomAppColor(0xFF242f1d);
  static const CustomAppColor primary160 = CustomAppColor(0xFF27321f);
  static const CustomAppColor primary170 = CustomAppColor(0xFF293521);
  static const CustomAppColor primary180 = CustomAppColor(0xFF2c3823);
  static const CustomAppColor primary190 = CustomAppColor(0xFF2e3b25);
  static const CustomAppColor primary200 = CustomAppColor(0xFF303e27);
  static const CustomAppColor primary220 = CustomAppColor(0xFF35452b);
  static const CustomAppColor primary240 = CustomAppColor(0xFF3a4b2f);
  static const CustomAppColor primary260 = CustomAppColor(0xFF3f5132);
  static const CustomAppColor primary280 = CustomAppColor(0xFF445736);
  static const CustomAppColor primary300 = CustomAppColor(0xFF495e3a);
  static const CustomAppColor primary350 = CustomAppColor(0xFF556d44);
  static const CustomAppColor primary400 = CustomAppColor(0xFF617d4e);
  static const CustomAppColor primary450 = CustomAppColor(0xFF6e8d58);
  static const CustomAppColor primary500 = CustomAppColor(0xFF7a9d61);
  static const CustomAppColor primary550 = CustomAppColor(0xFF87a671);
  static const CustomAppColor primary600 = CustomAppColor(0xFF94b081);
  static const CustomAppColor primary650 = CustomAppColor(0xFFa2ba91);
  static const CustomAppColor primary700 = CustomAppColor(0xFFafc4a0);
  static const CustomAppColor primary750 = CustomAppColor(0xFFbcceb0);
  static const CustomAppColor primary800 = CustomAppColor(0xFFc9d7c0);
  static const CustomAppColor primary810 = CustomAppColor(0xFFccd9c3);
  static const CustomAppColor primary820 = CustomAppColor(0xFFcfdbc6);
  static const CustomAppColor primary830 = CustomAppColor(0xFFd1ddc9);
  static const CustomAppColor primary840 = CustomAppColor(0xFFd4dfcc);
  static const CustomAppColor primary850 = CustomAppColor(0xFFd7e1cf);
  static const CustomAppColor primary860 = CustomAppColor(0xFFd9e3d3);
  static const CustomAppColor primary870 = CustomAppColor(0xFFdce5d6);
  static const CustomAppColor primary880 = CustomAppColor(0xFFdfe7d9);
  static const CustomAppColor primary890 = CustomAppColor(0xFFe1e9dc);
  static const CustomAppColor primary900 = CustomAppColor(0xFFe4ebdf);
  static const CustomAppColor primary910 = CustomAppColor(0xFFe7ede2);
  static const CustomAppColor primary920 = CustomAppColor(0xFFe9efe5);
  static const CustomAppColor primary930 = CustomAppColor(0xFFecf1e9);
  static const CustomAppColor primary940 = CustomAppColor(0xFFeff3ec);
  static const CustomAppColor primary950 = CustomAppColor(0xFFf1f5ef);
  static const CustomAppColor primary960 = CustomAppColor(0xFFf4f7f2);
  static const CustomAppColor primary970 = CustomAppColor(0xFFf7f9f5);
  static const CustomAppColor primary980 = CustomAppColor(0xFFf9fbf8);
  static const CustomAppColor primary990 = CustomAppColor(0xFFfcfdfb);
  static const CustomAppColor primary1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor secondary0 = CustomAppColor(0xFF000000);
  static const CustomAppColor secondary20 = CustomAppColor(0xFF0a0800);
  static const CustomAppColor secondary40 = CustomAppColor(0xFF141000);
  static const CustomAppColor secondary60 = CustomAppColor(0xFF1e1800);
  static const CustomAppColor secondary80 = CustomAppColor(0xFF282000);
  static const CustomAppColor secondary100 = CustomAppColor(0xFF332800);
  static const CustomAppColor secondary110 = CustomAppColor(0xFF382c00);
  static const CustomAppColor secondary120 = CustomAppColor(0xFF3d3000);
  static const CustomAppColor secondary130 = CustomAppColor(0xFF423400);
  static const CustomAppColor secondary140 = CustomAppColor(0xFF473800);
  static const CustomAppColor secondary150 = CustomAppColor(0xFF4c3c00);
  static const CustomAppColor secondary160 = CustomAppColor(0xFF514000);
  static const CustomAppColor secondary170 = CustomAppColor(0xFF564400);
  static const CustomAppColor secondary180 = CustomAppColor(0xFF5b4800);
  static const CustomAppColor secondary190 = CustomAppColor(0xFF604c00);
  static const CustomAppColor secondary200 = CustomAppColor(0xFF665000);
  static const CustomAppColor secondary220 = CustomAppColor(0xFF705800);
  static const CustomAppColor secondary240 = CustomAppColor(0xFF7a6000);
  static const CustomAppColor secondary260 = CustomAppColor(0xFF846800);
  static const CustomAppColor secondary280 = CustomAppColor(0xFF8e7000);
  static const CustomAppColor secondary300 = CustomAppColor(0xFF997800);
  static const CustomAppColor secondary350 = CustomAppColor(0xFFb28b00);
  static const CustomAppColor secondary400 = CustomAppColor(0xFFcca000);
  static const CustomAppColor secondary450 = CustomAppColor(0xFFe5b400);
  static const CustomAppColor secondary500 = CustomAppColor(0xFFffc800);
  static const CustomAppColor secondary550 = CustomAppColor(0xFFffcd19);
  static const CustomAppColor secondary600 = CustomAppColor(0xFFffd332);
  static const CustomAppColor secondary650 = CustomAppColor(0xFFfed84c);
  static const CustomAppColor secondary700 = CustomAppColor(0xFFffde65);
  static const CustomAppColor secondary750 = CustomAppColor(0xFFffe37f);
  static const CustomAppColor secondary800 = CustomAppColor(0xFFffe999);
  static const CustomAppColor secondary810 = CustomAppColor(0xFFffea9e);
  static const CustomAppColor secondary820 = CustomAppColor(0xFFfeeba3);
  static const CustomAppColor secondary830 = CustomAppColor(0xFFffeca8);
  static const CustomAppColor secondary840 = CustomAppColor(0xFFfeedad);
  static const CustomAppColor secondary850 = CustomAppColor(0xFFffeeb2);
  static const CustomAppColor secondary860 = CustomAppColor(0xFFfeefb7);
  static const CustomAppColor secondary870 = CustomAppColor(0xFFfff0bc);
  static const CustomAppColor secondary880 = CustomAppColor(0xFFfef1c1);
  static const CustomAppColor secondary890 = CustomAppColor(0xFFfff2c6);
  static const CustomAppColor secondary900 = CustomAppColor(0xFFfef3cc);
  static const CustomAppColor secondary910 = CustomAppColor(0xFFfff5d1);
  static const CustomAppColor secondary920 = CustomAppColor(0xFFfef6d6);
  static const CustomAppColor secondary930 = CustomAppColor(0xFFfff7db);
  static const CustomAppColor secondary940 = CustomAppColor(0xFFfff8e0);
  static const CustomAppColor secondary950 = CustomAppColor(0xFFfff9e5);
  static const CustomAppColor secondary960 = CustomAppColor(0xFFfffaea);
  static const CustomAppColor secondary970 = CustomAppColor(0xFFfffbef);
  static const CustomAppColor secondary980 = CustomAppColor(0xFFfffcf4);
  static const CustomAppColor secondary990 = CustomAppColor(0xFFfffdf9);
  static const CustomAppColor secondary1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor tertiary0 = CustomAppColor(0xFF000000);
  static const CustomAppColor tertiary20 = CustomAppColor(0xFF070302);
  static const CustomAppColor tertiary40 = CustomAppColor(0xFF0e0605);
  static const CustomAppColor tertiary60 = CustomAppColor(0xFF160908);
  static const CustomAppColor tertiary80 = CustomAppColor(0xFF1d0c0b);
  static const CustomAppColor tertiary100 = CustomAppColor(0xFF250f0d);
  static const CustomAppColor tertiary110 = CustomAppColor(0xFF28110f);
  static const CustomAppColor tertiary120 = CustomAppColor(0xFF2c1310);
  static const CustomAppColor tertiary130 = CustomAppColor(0xFF301412);
  static const CustomAppColor tertiary140 = CustomAppColor(0xFF341613);
  static const CustomAppColor tertiary150 = CustomAppColor(0xFF371714);
  static const CustomAppColor tertiary160 = CustomAppColor(0xFF3b1916);
  static const CustomAppColor tertiary170 = CustomAppColor(0xFF3f1a17);
  static const CustomAppColor tertiary180 = CustomAppColor(0xFF421c18);
  static const CustomAppColor tertiary190 = CustomAppColor(0xFF461e1a);
  static const CustomAppColor tertiary200 = CustomAppColor(0xFF4a1f1b);
  static const CustomAppColor tertiary220 = CustomAppColor(0xFF51221e);
  static const CustomAppColor tertiary240 = CustomAppColor(0xFF592621);
  static const CustomAppColor tertiary260 = CustomAppColor(0xFF602924);
  static const CustomAppColor tertiary280 = CustomAppColor(0xFF682c26);
  static const CustomAppColor tertiary300 = CustomAppColor(0xFF6f2f29);
  static const CustomAppColor tertiary350 = CustomAppColor(0xFF823730);
  static const CustomAppColor tertiary400 = CustomAppColor(0xFF943f37);
  static const CustomAppColor tertiary450 = CustomAppColor(0xFFa7473e);
  static const CustomAppColor tertiary500 = CustomAppColor(0xFFb94f45);
  static const CustomAppColor tertiary550 = CustomAppColor(0xFFc06057);
  static const CustomAppColor tertiary600 = CustomAppColor(0xFFc7726a);
  static const CustomAppColor tertiary650 = CustomAppColor(0xFFce847c);
  static const CustomAppColor tertiary700 = CustomAppColor(0xFFd5958f);
  static const CustomAppColor tertiary750 = CustomAppColor(0xFFdca7a2);
  static const CustomAppColor tertiary800 = CustomAppColor(0xFFe3b8b4);
  static const CustomAppColor tertiary810 = CustomAppColor(0xFFe4bcb8);
  static const CustomAppColor tertiary820 = CustomAppColor(0xFFe6bfbc);
  static const CustomAppColor tertiary830 = CustomAppColor(0xFFe7c3bf);
  static const CustomAppColor tertiary840 = CustomAppColor(0xFFe8c6c3);
  static const CustomAppColor tertiary850 = CustomAppColor(0xFFeacac7);
  static const CustomAppColor tertiary860 = CustomAppColor(0xFFebcdca);
  static const CustomAppColor tertiary870 = CustomAppColor(0xFFecd1ce);
  static const CustomAppColor tertiary880 = CustomAppColor(0xFFeed4d2);
  static const CustomAppColor tertiary890 = CustomAppColor(0xFFefd8d6);
  static const CustomAppColor tertiary900 = CustomAppColor(0xFFf1dbd9);
  static const CustomAppColor tertiary910 = CustomAppColor(0xFFf2dfdd);
  static const CustomAppColor tertiary920 = CustomAppColor(0xFFf3e2e1);
  static const CustomAppColor tertiary930 = CustomAppColor(0xFFf5e6e4);
  static const CustomAppColor tertiary940 = CustomAppColor(0xFFf6e9e8);
  static const CustomAppColor tertiary950 = CustomAppColor(0xFFf8edec);
  static const CustomAppColor tertiary960 = CustomAppColor(0xFFf9f0f0);
  static const CustomAppColor tertiary970 = CustomAppColor(0xFFfaf4f3);
  static const CustomAppColor tertiary980 = CustomAppColor(0xFFfcf7f7);
  static const CustomAppColor tertiary990 = CustomAppColor(0xFFfdfbfb);
  static const CustomAppColor tertiary1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor success0 = CustomAppColor(0xFF000000);
  static const CustomAppColor success20 = CustomAppColor(0xFF030900);
  static const CustomAppColor success40 = CustomAppColor(0xFF061201);
  static const CustomAppColor success60 = CustomAppColor(0xFF091c02);
  static const CustomAppColor success80 = CustomAppColor(0xFF0c2503);
  static const CustomAppColor success100 = CustomAppColor(0xFF0f2e04);
  static const CustomAppColor success110 = CustomAppColor(0xFF103304);
  static const CustomAppColor success120 = CustomAppColor(0xFF123805);
  static const CustomAppColor success130 = CustomAppColor(0xFF133c05);
  static const CustomAppColor success140 = CustomAppColor(0xFF154105);
  static const CustomAppColor success150 = CustomAppColor(0xFF164606);
  static const CustomAppColor success160 = CustomAppColor(0xFF184a06);
  static const CustomAppColor success170 = CustomAppColor(0xFF1a4f07);
  static const CustomAppColor success180 = CustomAppColor(0xFF1b5407);
  static const CustomAppColor success190 = CustomAppColor(0xFF1d5807);
  static const CustomAppColor success200 = CustomAppColor(0xFF1e5d08);
  static const CustomAppColor success220 = CustomAppColor(0xFF216709);
  static const CustomAppColor success240 = CustomAppColor(0xFF24700a);
  static const CustomAppColor success260 = CustomAppColor(0xFF27790a);
  static const CustomAppColor success280 = CustomAppColor(0xFF2a830b);
  static const CustomAppColor success300 = CustomAppColor(0xFF2d8c0c);
  static const CustomAppColor success350 = CustomAppColor(0xFF35a30e);
  static const CustomAppColor success400 = CustomAppColor(0xFF3dbb10);
  static const CustomAppColor success450 = CustomAppColor(0xFF44d212);
  static const CustomAppColor success500 = CustomAppColor(0xFF4cea14);
  static const CustomAppColor success550 = CustomAppColor(0xFF5eec2c);
  static const CustomAppColor success600 = CustomAppColor(0xFF70ee43);
  static const CustomAppColor success650 = CustomAppColor(0xFF82f05b);
  static const CustomAppColor success700 = CustomAppColor(0xFF93f272);
  static const CustomAppColor success750 = CustomAppColor(0xFFa5f489);
  static const CustomAppColor success800 = CustomAppColor(0xFFb7f6a1);
  static const CustomAppColor success810 = CustomAppColor(0xFFbbf7a6);
  static const CustomAppColor success820 = CustomAppColor(0xFFbef7aa);
  static const CustomAppColor success830 = CustomAppColor(0xFFc2f7af);
  static const CustomAppColor success840 = CustomAppColor(0xFFc5f8b4);
  static const CustomAppColor success850 = CustomAppColor(0xFFc9f8b8);
  static const CustomAppColor success860 = CustomAppColor(0xFFcdf9bd);
  static const CustomAppColor success870 = CustomAppColor(0xFFd0f9c2);
  static const CustomAppColor success880 = CustomAppColor(0xFFd4f9c6);
  static const CustomAppColor success890 = CustomAppColor(0xFFd7facb);
  static const CustomAppColor success900 = CustomAppColor(0xFFdbfad0);
  static const CustomAppColor success910 = CustomAppColor(0xFFdefbd4);
  static const CustomAppColor success920 = CustomAppColor(0xFFe2fbd9);
  static const CustomAppColor success930 = CustomAppColor(0xFFe6fcde);
  static const CustomAppColor success940 = CustomAppColor(0xFFe9fce2);
  static const CustomAppColor success950 = CustomAppColor(0xFFedfce7);
  static const CustomAppColor success960 = CustomAppColor(0xFFf0fdec);
  static const CustomAppColor success970 = CustomAppColor(0xFFf4fdf0);
  static const CustomAppColor success980 = CustomAppColor(0xFFf7fef5);
  static const CustomAppColor success990 = CustomAppColor(0xFFfbfefa);
  static const CustomAppColor success1000 = CustomAppColor(0xFFffffff);
  static const CustomAppColor yellow0 = CustomAppColor(0xFF000000);
  static const CustomAppColor yellow20 = CustomAppColor(0xFF0a0800);
  static const CustomAppColor yellow40 = CustomAppColor(0xFF141000);
  static const CustomAppColor yellow60 = CustomAppColor(0xFF1e1900);
  static const CustomAppColor yellow80 = CustomAppColor(0xFF282100);
  static const CustomAppColor yellow100 = CustomAppColor(0xFF332a00);
  static const CustomAppColor yellow110 = CustomAppColor(0xFF382e00);
  static const CustomAppColor yellow120 = CustomAppColor(0xFF3d3200);
  static const CustomAppColor yellow130 = CustomAppColor(0xFF423600);
  static const CustomAppColor yellow140 = CustomAppColor(0xFF473b00);
  static const CustomAppColor yellow150 = CustomAppColor(0xFF4c3f00);
  static const CustomAppColor yellow160 = CustomAppColor(0xFF514300);
  static const CustomAppColor yellow170 = CustomAppColor(0xFF564700);
  static const CustomAppColor yellow180 = CustomAppColor(0xFF5b4b00);
  static const CustomAppColor yellow190 = CustomAppColor(0xFF605000);
  static const CustomAppColor yellow200 = CustomAppColor(0xFF665400);
  static const CustomAppColor yellow220 = CustomAppColor(0xFF705c00);
  static const CustomAppColor yellow240 = CustomAppColor(0xFF7a6500);
  static const CustomAppColor yellow260 = CustomAppColor(0xFF846d00);
  static const CustomAppColor yellow280 = CustomAppColor(0xFF8e7600);
  static const CustomAppColor yellow300 = CustomAppColor(0xFF997e00);
  static const CustomAppColor yellow350 = CustomAppColor(0xFFb29300);
  static const CustomAppColor yellow400 = CustomAppColor(0xFFcca800);
  static const CustomAppColor yellow450 = CustomAppColor(0xFFe5bd00);
  static const CustomAppColor yellow500 = CustomAppColor(0xFFffd200);
  static const CustomAppColor yellow550 = CustomAppColor(0xFFffd719);
  static const CustomAppColor yellow600 = CustomAppColor(0xFFffdb32);
  static const CustomAppColor yellow650 = CustomAppColor(0xFFfee04c);
  static const CustomAppColor yellow700 = CustomAppColor(0xFFffe465);
  static const CustomAppColor yellow750 = CustomAppColor(0xFFffe87f);
  static const CustomAppColor yellow800 = CustomAppColor(0xFFffed99);
  static const CustomAppColor yellow810 = CustomAppColor(0xFFffee9e);
  static const CustomAppColor yellow820 = CustomAppColor(0xFFfeefa3);
  static const CustomAppColor yellow830 = CustomAppColor(0xFFfff0a8);
  static const CustomAppColor yellow840 = CustomAppColor(0xFFfef0ad);
  static const CustomAppColor yellow850 = CustomAppColor(0xFFfff1b2);
  static const CustomAppColor yellow860 = CustomAppColor(0xFFfef2b7);
  static const CustomAppColor yellow870 = CustomAppColor(0xFFfff3bc);
  static const CustomAppColor yellow880 = CustomAppColor(0xFFfef4c1);
  static const CustomAppColor yellow890 = CustomAppColor(0xFFfff5c6);
  static const CustomAppColor yellow900 = CustomAppColor(0xFFfef6cc);
  static const CustomAppColor yellow910 = CustomAppColor(0xFFfff7d1);
  static const CustomAppColor yellow920 = CustomAppColor(0xFFfef7d6);
  static const CustomAppColor yellow930 = CustomAppColor(0xFFfff8db);
  static const CustomAppColor yellow940 = CustomAppColor(0xFFfff9e0);
  static const CustomAppColor yellow950 = CustomAppColor(0xFFfffae5);
  static const CustomAppColor yellow960 = CustomAppColor(0xFFfffbea);
  static const CustomAppColor yellow970 = CustomAppColor(0xFFfffcef);
  static const CustomAppColor yellow980 = CustomAppColor(0xFFfffdf4);
  static const CustomAppColor yellow990 = CustomAppColor(0xFFfffef9);
  static const CustomAppColor yellow1000 = CustomAppColor(0xFFffffff);
}

class PrimitiveColors {
  static const CustomAppColor white = CustomAppColor(0xFFFFFFFF); // White
  static const CustomAppColor black = CustomAppColor(0xFF000000); // Black
  static const CustomAppColor transparent =
      CustomAppColor(0x00000000); // Transparent
  // Primary Colors
  static const CustomAppColor primary = CustomAppColor(0xFF5957D5); // Primary
  static const CustomAppColor primaryLight =
      CustomAppColor(0xFF9190E3); // Primary / Light
  static const CustomAppColor primaryGradient =
      CustomAppColor(0xFF6A00F4); // Gradient as a placeholder, adjust as needed

  // Secondary Colors
  static const CustomAppColor secondary =
      CustomAppColor(0xFF5F5F5F); // Secondary
  static const CustomAppColor secondaryDark =
      CustomAppColor(0xFF45495E); // Secondary Dark
  static const CustomAppColor secondaryLight =
      CustomAppColor(0xFF8A8B8E); // Secondary Light
  static const CustomAppColor green = CustomAppColor(0xFF27AE60); // Green
  static const CustomAppColor red = CustomAppColor(0xFFEB5757); // Red
  static const CustomAppColor gradient =
      CustomAppColor(0xFFEB5757); // Gradient as a placeholder

  static const CustomAppColor lightGrey =
      CustomAppColor(0xFFABABBE); // Light Grey
  static const CustomAppColor icons = CustomAppColor(0xFF414A58); // Icons

  // Status Colors
  static const CustomAppColor statusGreen = CustomAppColor(0xFF00801C); // Green
  static const CustomAppColor statusRed = CustomAppColor(0xFFDB0010); // Red
  static const CustomAppColor statusBlue = CustomAppColor(0xFF106CD9); // Blue
  static const CustomAppColor statusOrange =
      CustomAppColor(0xFFCE9200); // Orange
  static const CustomAppColor statusPurple =
      CustomAppColor(0xFF4F4EC8); // Purple

  static const CustomAppColor statusLightGreen =
      CustomAppColor(0xFFE6F8E6); // Light Green
  static const CustomAppColor statusLightRed =
      CustomAppColor(0xFFFEEAE7); // Light Red
  static const CustomAppColor statusLightBlue =
      CustomAppColor(0xFFEAF3FF); // Light Blue
  static const CustomAppColor statusLightOrange =
      CustomAppColor(0xFFFFF7E4); // Light Orange
  static const CustomAppColor statusLightPurple =
      CustomAppColor(0xFFEFF1FF); // Light Purple

  // Additional Status Colors
  static const CustomAppColor additionalLightBlue =
      CustomAppColor(0xFFD1EEFB); // Light Blue
  static const CustomAppColor additionalLightOrange =
      CustomAppColor(0xFFFEE4D9); // Light Orange
  static const CustomAppColor additionalLightPink =
      CustomAppColor(0xFFF3D9EE); // Light Pink
  static const CustomAppColor additionalLightRed =
      CustomAppColor(0xFFFCDDE0); // Light Red
  static const CustomAppColor additionalLightPurple =
      CustomAppColor(0xFFDEDDF7); // Light Purple

  // Purple Shades
  static const CustomAppColor purpleP0 = CustomAppColor(0xFFFFFFFF);
  static const CustomAppColor purpleP10 = CustomAppColor(0xFFFCFCFE);
  static const CustomAppColor purpleP20 = CustomAppColor(0xFFF8F8FD);
  static const CustomAppColor purpleP30 = CustomAppColor(0xFFF2F2FC);
  static const CustomAppColor purpleP40 = CustomAppColor(0xFFE9E9FA);
  static const CustomAppColor purpleP50 = CustomAppColor(0xFFD6D5F5);
  static const CustomAppColor purpleP60 = CustomAppColor(0xFFCCCBF2);
  static const CustomAppColor purpleP70 = CustomAppColor(0xFFC3C3F0);
  static const CustomAppColor purpleP80 = CustomAppColor(0xFFB8B8ED);
  static const CustomAppColor purpleP90 = CustomAppColor(0xFFAEAEEB);
  static const CustomAppColor purpleP100 = CustomAppColor(0xFFA5A4E8);
  static const CustomAppColor purpleP200 = CustomAppColor(0xFF9B9AE6);
  static const CustomAppColor purpleP300 = CustomAppColor(0xFF9190E3);
  static const CustomAppColor purpleP400 = CustomAppColor(0xFF8988E1);
  static const CustomAppColor purpleP500 = CustomAppColor(0xFF7F7EDF);
  static const CustomAppColor purpleP600 = CustomAppColor(0xFF7775DD);
  static const CustomAppColor purpleP700 = CustomAppColor(0xFF6B69DA);
  static const CustomAppColor purpleP800 = CustomAppColor(0xFF615FD7);
  static const CustomAppColor purpleP900 = CustomAppColor(0xFF5957D5);

  // Gray Colors
  static const CustomAppColor grayG0 = CustomAppColor(0xFFFFFFFF);
  static const CustomAppColor grayG10 = CustomAppColor(0xFFFAFAFA);
  static const CustomAppColor grayG20 = CustomAppColor(0xFFF6F6F6);
  static const CustomAppColor grayG30 = CustomAppColor(0xFFEEEEEE);
  static const CustomAppColor grayG40 = CustomAppColor(0xFFE2E2E2);
  static const CustomAppColor grayG50 = CustomAppColor(0xFFC7C7C7);
  static const CustomAppColor grayG60 = CustomAppColor(0xFFB9B9B9);
  static const CustomAppColor grayG70 = CustomAppColor(0xFFAEAEAE);
  static const CustomAppColor grayG80 = CustomAppColor(0xFFA0A0A0);
  static const CustomAppColor grayG90 = CustomAppColor(0xFF939393);
  static const CustomAppColor grayG100 = CustomAppColor(0xFF858585);
  static const CustomAppColor grayG300 = CustomAppColor(0xFF6A6A6A);
  static const CustomAppColor grayG500 = CustomAppColor(0xFF515151);
  static const CustomAppColor grayG600 = CustomAppColor(0xFF464646);
  static const CustomAppColor grayG700 = CustomAppColor(0xFF363636);
  static const CustomAppColor grayG900 = CustomAppColor(0xFF1D1D1D);

  // Dark Gray Colors
  static const CustomAppColor darkGrayD50 = CustomAppColor(0xFFF5F5F7);
  static const CustomAppColor darkGrayD100 = CustomAppColor(0xFFF0F0F7);
  static const CustomAppColor darkGrayD200 = CustomAppColor(0xFFD0D0DB);
  static const CustomAppColor darkGrayD300 = CustomAppColor(0xFF8888CA);
  static const CustomAppColor darkGrayD400 = CustomAppColor(0xFFA4ADC0);
  static const CustomAppColor darkGrayD500 = CustomAppColor(0xFF999980);
  static const CustomAppColor darkGrayD600 = CustomAppColor(0xFF8888AD);
  static const CustomAppColor darkGrayD700 = CustomAppColor(0xFF606D7D);
  static const CustomAppColor darkGrayD800 = CustomAppColor(0xFF545461);
  static const CustomAppColor darkGrayD900 = CustomAppColor(0xFF40404A);

// Primary Colors
  static const CustomAppColor primaryInactive = CustomAppColor(0xFF9190E3);
  static const CustomAppColor stroke = CustomAppColor(0xFFD0D0DB);
  static const CustomAppColor dark = CustomAppColor(0xFF282828);
  static const CustomAppColor additionalPurple = CustomAppColor(0xFFEFF1FF);
  static const CustomAppColor additionalGreen = CustomAppColor(0xFF27AE60);
  static const CustomAppColor additionalRed = CustomAppColor(0xFFEB5757);
  static const CustomAppColor additionalDark = CustomAppColor(0xFF616161);
  static const CustomAppColor additionalLight = CustomAppColor(0xFF8B8AAC);
  static const CustomAppColor additionalIcons = CustomAppColor(0xFF777777);

  // Text Colors
  static const CustomAppColor textMain = CustomAppColor(0xFF2C323A);
  static const CustomAppColor textSecondary = CustomAppColor(0xFF464646);
  static const CustomAppColor textActive = CustomAppColor(0xFF363636);
  static const CustomAppColor textInactive = CustomAppColor(0xFF777777);
  static const CustomAppColor textLight = CustomAppColor(0xFFFAFAFA);

  // Status Colors
  static const CustomAppColor lightBlue = CustomAppColor(0xFFd1eefb);
  static const CustomAppColor lightOrange = CustomAppColor(0xFFfee4d9);
  static const CustomAppColor lightPink = CustomAppColor(0xFFf3d9ee);
  static const CustomAppColor lightRed = CustomAppColor(0xFFfcdbe0);
  static const CustomAppColor lightPurple = CustomAppColor(0xFFdeddf7);

  // Others
  static const CustomAppColor neonPink = CustomAppColor(0xFFD557B1);
}
