// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkTJ6f93i2-W7mVWmxra-nXZujNW-q8o',
    appId: '1:744529295223:web:a19bcbcaca1fa80f3f9372',
    messagingSenderId: '744529295223',
    projectId: 'jigunuapi',
    authDomain: 'jigunuapi.firebaseapp.com',
    storageBucket: 'jigunuapi.firebasestorage.app',
    measurementId: 'G-54CZ535NP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbhlQBoZeCTtf7AfINENYrsBvFh7vDAo',
    appId: '1:744529295223:android:c07b7e0196242de53f9372',
    messagingSenderId: '744529295223',
    projectId: 'jigunuapi',
    storageBucket: 'jigunuapi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2yqUV6YVoYRAHx3MS802YZFLakfZGhA',
    appId: '1:744529295223:ios:1d14815bb27ab7203f9372',
    messagingSenderId: '744529295223',
    projectId: 'jigunuapi',
    storageBucket: 'jigunuapi.firebasestorage.app',
    androidClientId:
        '744529295223-vl3vs73gh6thdhjm5easdta8jtfru894.apps.googleusercontent.com',
    iosClientId:
        '744529295223-cr37cksiokqgd66js3g3lal7jto7ask7.apps.googleusercontent.com',
    iosBundleId: 'com.techjar.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2yqUV6YVoYRAHx3MS802YZFLakfZGhA',
    appId: '1:744529295223:ios:1d14815bb27ab7203f9372',
    messagingSenderId: '744529295223',
    projectId: 'jigunuapi',
    storageBucket: 'jigunuapi.firebasestorage.app',
    androidClientId:
        '744529295223-vl3vs73gh6thdhjm5easdta8jtfru894.apps.googleusercontent.com',
    iosClientId:
        '744529295223-cr37cksiokqgd66js3g3lal7jto7ask7.apps.googleusercontent.com',
    iosBundleId: 'com.techjar.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnkTJ6f93i2-W7mVWmxra-nXZujNW-q8o',
    appId: '1:744529295223:web:2a7d77dd6efd3d333f9372',
    messagingSenderId: '744529295223',
    projectId: 'jigunuapi',
    authDomain: 'jigunuapi.firebaseapp.com',
    storageBucket: 'jigunuapi.firebasestorage.app',
    measurementId: 'G-R4G9MNDKFD',
  );
}
